# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=5)),
                ('image', models.CharField(max_length=15)),
            ],
        ),
    ]
