# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=18)),
                ('zipcode', models.CharField(max_length=6)),
                ('quantity', models.CharField(max_length=5)),
                ('total', models.CharField(max_length=5)),
                ('ccnumber', models.CharField(max_length=16)),
                ('ccexpiration', models.CharField(max_length=6)),
            ],
        ),
    ]
