# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.CharField(max_length=10),
        ),
    ]
