# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20160429_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(default='city', max_length=30),
        ),
    ]
